# -*- coding: utf-8 -*-
"""PCA.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WgfAF7ccLF7eD2_WwSilXW765NCndtkw
"""

import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import seaborn as snst

from sklearn.datasets import load_breast_cancer
can = load_breast_cancer()

can.keys()

print(can['DESCR'])

df = pd.DataFrame(can['data'],columns=can['feature_names'])

df.head()

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(df)

scaled_data = scaler.transform(df)

from sklearn.decomposition import PCA

pca = PCA(n_components=2)
pca.fit(scaled_data)

x_pca = pca.transform(scaled_data)

scaled_data.shape

x_pca.shape

plt.figure(figsize=(8,6))
plt.scatter(x_pca[:,0],x_pca[:,1],c=can['target'],cmap='plasma')
plt.xlabel('First principal component')
plt.ylabel('Second Principal Component')

pca.components_

pca.components_

